#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.MobileInfo."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_MobileInfo"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_MobileInfo"
MDCOLLECTCTL_BIN=/usr/bin/mdcollectdctl
current_sim="1"
# Structure --- <Value name represented in easycwmp log;ubus method name;lookup value from method response>
PARAM_LIST="RSSI;get_signal_query;rssi ConnState;get_net_reg_stat;status_id NetState;get_net_reg_stat;status ICCID;get_iccid;iccid \
IMSI;get_imsi;imsi RSCP;null;null ECIO;null;null RSRP;get_signal_query;rsrp SINR;get_signal_query;sinr RSRQ;get_signal_query;rsrq \
CellID;get_net_reg_stat;ci Operator;get_operator_selection;operator OperatorNum;get_network_info;opernum ConnType;get_signal_query;net_mode \
Model;info;model Manufacturer;info;manuf Serial;get_serial;serial Revision;get_firmware;firmware IMEI;info;imei SimState;get_pin_state;state_id \
PinState;get_pin_state;state Temperature;get_temperature;temperature_value"

MODEMS=""

get_modems(){

	local modem_objs=$(ubus list gsm.*)
	for i in $modem_objs
	do
		MODEMS=${MODEMS:+$MODEMS }"${i//[!0-9]/}"
	done

}

get_usb_id() {

	local modem_num="$1"
	local usb_id="$(ubus call gsm.modem$modem_num info 2>/dev/null | grep usb_id | sed 's/.* //g')"

	echo "${usb_id:1:-2}"

}

get_modem_value() {

	local modem_num="$1"
	local method="$2"
	local value="$3"
	local parameter_name="$4"

	local found_value=$(ubus call gsm.modem$modem_num $method 2>/dev/null | grep -w $value | sed 's/[^ ]* *//; s/["]//g; s/,$//g')

	case "$parameter_name" in
		"SimState")
			case "$found_value" in
				"1"|"3"|"4"|"5"|"6"|"7"|"8"|"11")
					found_value="Inserted"
				;;
				*)
					found_value="Not inserted"
				;;
			esac
		;;
		"ConnState")
			[ "$found_value" == "1" ] || [ "$found_value" == "5" ] && found_value="Connected" || found_value="Not connected"
		;;
		"Operator")
			local format=$(ubus call gsm.modem$modem_num $method 2>/dev/null | grep -w format | sed 's/[^ ]* *//; s/["]//g; s/,$//g')
			if [ "$format" == "Numeric" ];
			then
				/bin/ubus call gsm.modem"$modem_num" set_operator_selection "{\"format\":\"short\"}" >> /dev/null 2>&1

				found_value=$(ubus call gsm.modem$modem_num $method 2>/dev/null | grep -w $value | sed 's/[^ ]* *//; s/["]//g; s/,$//g')

				/bin/ubus call gsm.modem"$modem_num" set_operator_selection "{\"format\":\"numeric\"}" >> /dev/null 2>&1
			fi
		;;
	esac

	echo "$found_value"

}

list_foreach(){
	[ "$#" -ge 2 ] || return 0
	local list=$1; shift
	local callback=$1; shift

	for element in $list
	do
		$callback $element $@
	done
}

entry_execute_method_root_MobileInfo() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.MobileInfo."*)
		common_execute_method_obj "$DMROOT.MobileInfo." "0"
		common_execute_method_obj "$DMROOT.MobileInfo.Modem." "0" "" "" "mobileinfo_browse_modems $1"

		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_modem_info(){
	name=$(echo $1 | awk 'BEGIN { FS = ";" }; {print $1}')
	method=$(echo $1 | awk 'BEGIN { FS = ";" }; {print $2}')
	value=$(echo $1 | awk 'BEGIN { FS = ";" }; {print $3}')

	local usb_id="$2"
	local modem_num="$3"

	local modem_value=$(get_modem_value "$modem_num" "$method" "$value" "$name")

	[ -n "$name" -a -n "$method" ] && {
		common_execute_method_param "$DMROOT.MobileInfo.Modem.$usb_id.$name" "0"\
		 	"echo $modem_value" "" "" "1"
	}
}

sub_entry_modem() {
	local modem sim=1
	local modem_num="$1"

	modem=$(get_usb_id "$modem_num")

	case_param "$2" belongto "$DMROOT.MobileInfo.Modem.$modem." && {
		common_execute_method_obj "$DMROOT.MobileInfo.Modem.$modem." "0"
		list_foreach "$PARAM_LIST" sub_entry_modem_info $modem $modem_num
		common_execute_method_param "$DMROOT.MobileInfo.Modem.$modem.SentToday" "0" \
			"get_sent_today $modem $sim" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.Modem.$modem.ReceivedToday" "0" \
			"get_received_today $modem $sim" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.Modem.$modem.SentThisMonth" "0" \
			"get_sent_month $modem $sim" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.Modem.$modem.ReceivedThisMonth" "0" \
			"get_received_month $modem $sim" "" "" "1"

		return 0
	}
	return "$E_INVALID_PARAMETER_NAME"
}

mobileinfo_browse_modems() {
	#We're not using json_for_each_item here, cus json is overwrited by system.
	[ -n "$MODEMS" ] || get_modems

	list_foreach "$MODEMS" sub_entry_modem "$1"
}

get_sent_today() {
	json_load "$(ubus call mdcollect get \
		 '{"modem": "'$1'", "sim": '$2', "period": "day", "current": false}')"
	json_get_var sent_today tx

	echo "$sent_today"
}

get_received_today() {
	json_load "$(ubus call mdcollect get \
		'{"modem": "'$1'", "sim": '$2', "period": "day", "current": false}')"
	json_get_var received_today rx

	echo "$received_today"
}

get_sent_month() {
	json_load "$(ubus call mdcollect get \
		'{"modem": "'$1'", "sim": '$2', "period": "month", "current": false}')"
	json_get_var sent_month tx 

	echo "$sent_month"
}

get_received_month() {
	json_load "$(ubus call mdcollect get \
		'{"modem": "'$1'", "sim": '$2', "period": "month", "current": false}')"
	json_get_var received_month rx

	echo "$received_month"
}

#######################################
#   Data model parameters functions   #
#######################################
