#!/bin/sh

. /lib/functions.sh

CONFIG="widget"
MOBILE_CONFIG="/etc/config/simcard"
RMS_CONFIG="/etc/config/rms_mqtt"
WIFI_CONFIG="/etc/config/wireless"
ETHERNET=$(uci_get network @switch[0] name)
ethernet_widget_exists=0
mobile_widget_exists=0
system_widget_exists=0
wifi_widget_exists=0
rms_widget_exists=0
position=1
radio0_network=1
radio1_network=1
isTAP=$(mnf_info --name | grep -q TAP100 ; echo $?)

check_for_widgets() {
	local widget="$1"
	local type
	config_get type "$widget" "type"

	if [ "$type" = "ethernet" ]; then
		ethernet_widget_exists=1
	elif [ "$type" = "mobile" ]; then
		mobile_widget_exists=1
	elif [ "$type" = "system" ]; then
		system_widget_exists=1
	elif [ "$type" = "wifi" ]; then
		wifi_widget_exists=1
	elif [ "$type" = "rms" ]; then
		rms_widget_exists=1
	fi
}

setup_wifi_fields() {
	local iface_section="$1"
	local device
	config_get device "$iface_section" "device"

	# Exception of not using library because lib does not return a value!
	section=$(uci -q add widget widget)
	
	if [ "$device" = "radio0" ]; then
		uci_set "$CONFIG" "$section" "id" "${device}.network${radio0_network}"
		radio0_network=$((radio0_network + 1))
	elif [ "$device" = "radio1" ]; then
		uci_set "$CONFIG" "$section" "id" "${device}.network${radio1_network}"
		radio1_network=$((radio1_network + 1))
	fi

	uci_set "$CONFIG" "$section" "type" "wifi"
	uci_set "$CONFIG" "$section" "position" "${position}"
	uci_set "$CONFIG" "$section" "enabled" "1"
	position=$((position + 1))
}

check_if_config_exists() {
	if [ ! -f "/etc/config/${CONFIG}" ]; then
		touch "/etc/config/${CONFIG}"
	fi
}

setup_side_widget() {
	config_load "widget"
	config_foreach check_for_widgets "widget"

	if [ "$ethernet_widget_exists" -eq 0 ] && [ -n "$ETHERNET" ]; then
		check_if_config_exists

		# Another exception
		section=$(uci -q add widget widget)
		uci_set "$CONFIG" "$section" "id" "widget1"
		uci_set "$CONFIG" "$section" "type" "ethernet"
		uci_set "$CONFIG" "$section" "position" "$position"
		uci_set "$CONFIG" "$section" "enabled" "1"
		position=$((position + 1))
	fi

	if [ "$mobile_widget_exists" -eq 0 ] && [ -s "$MOBILE_CONFIG" ] && [ -f "$MOBILE_CONFIG" ]; then
		check_if_config_exists
		modem_count=$(jsonfilter -q -i /etc/board.json  -e '@["modems"][*]' | wc -l)

		for i in $(seq "$modem_count"); do
			# And another one...
			section=$(uci -q add widget widget)
			uci_set "$CONFIG" "$section" "id" "mobile-widget${i}"
			uci_set "$CONFIG" "$section" "type" "mobile"
			uci_set "$CONFIG" "$section" "position" "$position"
			uci_set "$CONFIG" "$section" "enabled" "1"
			position=$((position + 1))
		done
	fi

	if [ "$system_widget_exists" -eq 0 ]; then
		check_if_config_exists

		# These just keep on coming
		section=$(uci -q add widget widget)
		uci_set "$CONFIG" "$section" "id" "widget3"
		uci_set "$CONFIG" "$section" "type" "system"
		uci_set "$CONFIG" "$section" "position" "$position"
		uci_set "$CONFIG" "$section" "enabled" "1"
		position=$((position + 1))
	fi

	if [ "$wifi_widget_exists" -eq 0 ] && [ -f "$WIFI_CONFIG" ]; then
		check_if_config_exists
		config_load wireless
		config_foreach setup_wifi_fields wifi-iface
	fi

	if [ "$rms_widget_exists" -eq 0 ] && [ -f "$RMS_CONFIG" ]; then
		check_if_config_exists

		# Well...
		section=$(uci -q add widget widget)
		uci_set "$CONFIG" "$section" "id" "widget5"
		uci_set "$CONFIG" "$section" "type" "rms"
		uci_set "$CONFIG" "$section" "position" "$position"
		uci_set "$CONFIG" "$section" "enabled" "1"
		position=$((position + 1))
	fi

	uci_commit "$CONFIG"
}

[ $isTAP -eq 0 ] && exit 0
setup_side_widget
exit 0
