#!/bin/sh

. /lib/functions.sh
CONFIG="network"

update_pdp() {
	local section="$1"

	config_get net_proto "$section" "proto"

	[ "$net_proto" != "wwan" ] && return 0

	config_get mobile_pdp "$section" "pdp"
	config_get mobile_pdp_type "$section" "pdptype"

	[ "$mobile_pdp_type" == "ip" ] || [ "$mobile_pdp_type" == "ipv6" ] ||\
	[ "$mobile_pdp_type" == "ipv4v6" ] && return 0

	case "$mobile_pdp_type" in
	"1")
		uci_set "$CONFIG" "$section" "pdptype" "ip"
		;;
	"2")
		uci_set "$CONFIG" "$section" "pdptype" "ipv6"
		;;
	"3")
		uci_set "$CONFIG" "$section" "pdptype" "ipv4v6"
		;;
	*)
		uci_set "$CONFIG" "$section" "pdptype" "ip"
		;;
	esac

	[ "$mobile_pdp" -lt 8 ] && [ "$mobile_pdp" -gt 3 ] && {
		uci_set "$CONFIG" "$section" "pdp" "$((mobile_pdp + 8))"
	}
}

remove_auto() {
	local section="$1"
	local auto proto enabled disabled

	config_get auto "$section" "auto"
	config_get proto "$section" "proto"
	config_get enabled "$section" "enabled"
	config_get disabled "$section" "disabled"

	[ -n "$auto" ] && [ "$proto" != "gre" ] && {
		[ -z "$disabled" ] && {
			if [ -n "$enabled" ];then
				[ "$enabled" = "0" ] && uci_set "network" "$section" "disabled" "1"
				uci_remove "network" "$section" "enabled"
			else
				[ "$auto" = "0" ] && uci_set "network" "$section" "disabled" "1"
			fi
		}
		uci_remove "network" "$section" "auto"
	}
}

config_load "$CONFIG"
config_foreach update_pdp "interface"
config_foreach remove_auto "interface"
uci_commit "$CONFIG"
