#!/bin/sh

. /lib/functions.sh

rename_l2tp_client() {
	config_get proto "$1" "proto"
	[ "$proto" = "l2tp" ] && {
		config_get name "$1" "_name"
		uci_rename "network" "$1" "$name"
	}
}

config_load "network"
config_foreach rename_l2tp_client "interface"
uci_commit "network"
